#!/bin/sh

screen -dmS imp52 ./h316 ./imp52.simh >imp52.log 2>&1 &
screen -dmS imp53 ./h316 ./imp53.simh >imp53.log 2>&1 &
screen -dmS imp54 ./h316 ./imp54.simh >imp54.log 2>&1 &
screen -dmS imp55 ./h316 ./imp55.simh >imp55.log 2>&1 &
screen -dmS imp62 ./h316 ./imp62.simh >imp62.log 2>&1 &
echo "Arpanet IMP"

export NCP="$PWD/ncp52"
rm -f "$NCP"
screen -dmS ncp52 ./ncpd localhost 22001 22002 2>ncp52.log &

export NCP="$PWD/ncp53"
rm -f "$NCP"
screen -dmS ncp53 ./ncpd localhost 22003 22004 2>ncp53.log &

export NCP="$PWD/ncp54"
rm -f "$NCP"
screen -dmS ncp54 ./ncpd localhost 22005 22006 2>ncp54.log &

export NCP="$PWD/ncp55"
rm -f "$NCP"
screen -dmS ncp55 ./ncpd localhost 22007 22008 2>ncp55.log &

export NCP="$PWD/ncp62"
rm -f "$NCP"
screen -dmS ncp62 ./ncpd localhost 22101 22102 2>ncp076.log &
echo "Local NCP daemon"

sleep 3

./pdp10-ka ./mini-run

./stop
